services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geolocation
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  pgadmin:
        image: dpage/pgadmin4:latest
        environment:
          PGADMIN_DEFAULT_EMAIL: "admin@example.com" # Change as needed
          PGADMIN_DEFAULT_PASSWORD: "admin"         # Change as needed
          PGADMIN_CONFIG_SERVER_MODE: "False"       # Run in desktop mode
        ports:
          - "5050:80" # Access pgAdmin on http://localhost:5050
        depends_on:
          - db
        volumes:
          - pgadmin_data:/var/lib/pgadmin

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/geolocation
      - IPSTACK_API_KEY=${IPSTACK_API_KEY}
      - APP_LOG_FORMAT=${APP_LOG_FORMAT:-json}
    volumes:
      - ./app:/app/app
      - ./pytest.ini:/app/pytest.ini
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
      - ./scripts:/app/scripts
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  db_data:
  pgadmin_data:
